export const LOADED_3BOX = '3box.LOADED_3BOX';
export const SKILLS_UPDATED = '3box.SKILLS_UPDATED';
export const ATTESTATIONS_UPDATED = '3box.ATTESTATIONS_UPDATED';
export const PENDING_ATTESTATIONS_UPDATED = '3box.PENDING_ATTESTATIONS_UPDATED';
export const PUBLIC_PROFILE_LOADED = '3box.PUBLIC_PROFILE_LOADED';



